Repository esdc-devcop/recommendations, pull requests merged in 2019-11, with the labels that each got.

#6 Add TFS 2015 Recommendation
  README.md
  assets/pictures/AreasTFS2015.PNG
  assets/pictures/BranchingMergingRnDTFVC.JPG
  assets/pictures/BranchingMergingTFVC.JPG
  assets/pictures/IterationsTFS2015.PNG
  assets/pictures/TFSTasksDiagram.png
  tools/tfs2015.md
Labels: documentation, migration, recommendation

#9 Migrating and splitting git docs
  README.md
  source_management/git-branching.md
  source_management/merging-review.md
Labels: documentation, migration, recommendation

#12 Adding Jemoji plugin
  Gemfile
  _config.yml
Labels: enhancement

#13 Fixing the emoji styles from transfer of doc
  source_management/git-branching.md
Labels: bug

#17 Add menu into template
  _data/nav.yml
  _layouts/default.html
Labels: documentation

#14 Create AutomatedA11yTesting.md
  README.md
  Testing/AutomatedA11yTesting.md
Labels: migration, recommendation

#18 Move files and add separated index
  README.md
  index.md
  testing/auto-a11y.md
  tools/artifactory.md
Labels: documentation

#19 Adding some thoughts to FAQ
  source_management/merging-review.md
Labels: documentation, question

#20 Including best practices from GitLab
  source_management/merging-review.md
Labels: documentation, recommendation
